from html import escape

# A compact, locally bundled utility/component stylesheet for the server-rendered
# portal. It follows Tailwind utility naming/tokens and shadcn-style component
# conventions without requiring a React/Vite or Node runtime on the host.
APP_CSS = r'''
:root{
  color-scheme:light;
  --background:#f8fafc;--foreground:#0f172a;--muted:#64748b;--muted-foreground:#64748b;
  --card:#ffffff;--card-foreground:#0f172a;--border:#e2e8f0;--input:#cbd5e1;
  --primary:#4f46e5;--primary-hover:#4338ca;--primary-foreground:#fff;
  --secondary:#f1f5f9;--secondary-foreground:#0f172a;
  --destructive:#dc2626;--destructive-hover:#b91c1c;--ring:#6366f1;
  --success:#059669;--warning:#d97706;--danger:#dc2626;
  --radius:12px;--shadow-sm:0 1px 2px rgba(15,23,42,.05);--shadow:0 8px 28px rgba(15,23,42,.08);
}
*{box-sizing:border-box}html{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}body{margin:0;background:var(--background);color:var(--foreground)}button,input{font:inherit}button{border:0}a{color:inherit}::selection{background:#c7d2fe;color:#1e1b4b}
.hidden{display:none!important}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.min-h-screen{min-height:100vh}.w-full{width:100%}.max-w-7xl{max-width:80rem}.mx-auto{margin-left:auto;margin-right:auto}.flex{display:flex}.grid{display:grid}.items-center{align-items:center}.justify-between{justify-content:space-between}.gap-2{gap:.5rem}.gap-3{gap:.75rem}.gap-4{gap:1rem}.gap-6{gap:1.5rem}.text-sm{font-size:.875rem}.text-xs{font-size:.75rem}.font-medium{font-weight:500}.font-semibold{font-weight:600}.font-bold{font-weight:700}.text-muted{color:var(--muted)}
.app-grid-bg{position:relative;isolation:isolate}.app-grid-bg:before{content:"";position:fixed;inset:0;z-index:-2;background:radial-gradient(circle at 10% 0%,rgba(99,102,241,.09),transparent 30%),radial-gradient(circle at 92% 8%,rgba(14,165,233,.07),transparent 24%),linear-gradient(#f8fafc,#f8fafc)}.app-grid-bg:after{content:"";position:fixed;inset:0;z-index:-1;opacity:.32;background-image:linear-gradient(rgba(148,163,184,.14) 1px,transparent 1px),linear-gradient(90deg,rgba(148,163,184,.14) 1px,transparent 1px);background-size:32px 32px;mask-image:linear-gradient(to bottom,black,transparent 78%)}
.ui-card{background:rgba(255,255,255,.96);border:1px solid var(--border);border-radius:var(--radius);box-shadow:var(--shadow-sm)}.ui-card-elevated{box-shadow:var(--shadow)}
.ui-button{display:inline-flex;align-items:center;justify-content:center;gap:.5rem;min-height:40px;border-radius:9px;padding:.625rem 1rem;font-weight:600;font-size:.875rem;cursor:pointer;transition:background .15s ease,color .15s ease,border-color .15s ease,box-shadow .15s ease,transform .15s ease;text-decoration:none;white-space:nowrap}.ui-button:focus-visible,.ui-input:focus-visible,.ui-icon-button:focus-visible{outline:3px solid rgba(99,102,241,.25);outline-offset:2px}.ui-button:disabled{opacity:.55;cursor:not-allowed;transform:none}.ui-button-primary{background:var(--primary);color:var(--primary-foreground);box-shadow:0 1px 2px rgba(79,70,229,.2)}.ui-button-primary:hover:not(:disabled){background:var(--primary-hover)}.ui-button-secondary{background:#fff;color:#334155;border:1px solid var(--border)}.ui-button-secondary:hover:not(:disabled){background:#f8fafc;border-color:#cbd5e1}.ui-button-ghost{background:transparent;color:#475569}.ui-button-ghost:hover:not(:disabled){background:#f1f5f9;color:#0f172a}.ui-button-danger{background:#fff;color:var(--destructive);border:1px solid #fecaca}.ui-button-danger:hover:not(:disabled){background:#fef2f2;border-color:#fca5a5}.ui-icon-button{display:inline-flex;align-items:center;justify-content:center;width:40px;height:40px;border-radius:9px;background:transparent;color:#475569;cursor:pointer;transition:.15s}.ui-icon-button:hover{background:#f1f5f9;color:#0f172a}
.ui-input{width:100%;height:42px;border:1px solid var(--input);border-radius:9px;background:#fff;color:var(--foreground);padding:0 .8rem;outline:none;transition:border-color .15s,box-shadow .15s}.ui-input::placeholder{color:#94a3b8}.ui-input:hover{border-color:#94a3b8}.ui-input:focus{border-color:var(--ring);box-shadow:0 0 0 3px rgba(99,102,241,.14)}.ui-label{display:block;font-size:.8125rem;font-weight:600;color:#334155;margin-bottom:.45rem}
.ui-badge{display:inline-flex;align-items:center;gap:.35rem;border-radius:999px;padding:.25rem .55rem;font-size:.72rem;font-weight:700;line-height:1;border:1px solid transparent;text-transform:capitalize}.badge-running{background:#ecfdf5;color:#047857;border-color:#a7f3d0}.badge-starting,.badge-stopping{background:#fffbeb;color:#b45309;border-color:#fde68a}.badge-stopped{background:#f1f5f9;color:#475569;border-color:#e2e8f0}.badge-error{background:#fef2f2;color:#b91c1c;border-color:#fecaca}.status-dot{width:7px;height:7px;border-radius:50%;background:#10b981;box-shadow:0 0 0 3px rgba(16,185,129,.12)}
.ui-alert{display:flex;gap:.75rem;align-items:flex-start;border-radius:10px;border:1px solid #fde68a;background:#fffbeb;color:#92400e;padding:.85rem 1rem;font-size:.875rem}.ui-alert-error{border-color:#fecaca;background:#fef2f2;color:#991b1b}.ui-alert-success{border-color:#a7f3d0;background:#ecfdf5;color:#065f46}
.ui-spinner{width:18px;height:18px;border:2px solid currentColor;border-right-color:transparent;border-radius:50%;animation:spin .72s linear infinite}.ui-spinner-lg{width:38px;height:38px;border-width:3px}@keyframes spin{to{transform:rotate(360deg)}}
.icon{width:18px;height:18px;display:block;flex:0 0 auto}.icon-sm{width:15px;height:15px}.brand-mark{width:40px;height:40px;border-radius:11px;display:grid;place-items:center;background:linear-gradient(135deg,#4f46e5,#2563eb);color:#fff;box-shadow:0 8px 20px rgba(79,70,229,.22)}
/* Login */
.login-shell{min-height:100vh;display:grid;grid-template-columns:minmax(0,1.08fr) minmax(420px,.92fr);background:#fff}.login-visual{position:relative;overflow:hidden;display:flex;flex-direction:column;justify-content:space-between;padding:clamp(2rem,5vw,4.75rem);color:#e2e8f0;background:radial-gradient(circle at 20% 0%,rgba(99,102,241,.45),transparent 34%),radial-gradient(circle at 100% 30%,rgba(14,165,233,.25),transparent 28%),linear-gradient(145deg,#0f172a 5%,#172554 50%,#111827 100%)}.login-visual:before{content:"";position:absolute;inset:0;opacity:.22;background-image:linear-gradient(rgba(255,255,255,.12) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.12) 1px,transparent 1px);background-size:38px 38px;mask-image:linear-gradient(to bottom right,black,transparent 78%)}.login-visual>*{position:relative;z-index:1}.login-brand{display:flex;align-items:center;gap:.85rem;font-weight:700;color:#fff}.login-brand small{display:block;font-weight:500;color:#94a3b8;margin-top:.12rem}.login-hero{max-width:690px;padding:4rem 0}.login-kicker{display:inline-flex;align-items:center;gap:.45rem;border:1px solid rgba(255,255,255,.15);background:rgba(255,255,255,.06);border-radius:999px;padding:.35rem .65rem;font-size:.75rem;font-weight:600;color:#cbd5e1;backdrop-filter:blur(10px)}.login-hero h1{font-size:clamp(2.4rem,4.6vw,4.6rem);line-height:1.02;letter-spacing:-.045em;margin:1.25rem 0 1.1rem;color:#fff;max-width:760px}.login-hero p{font-size:1.05rem;line-height:1.7;color:#cbd5e1;max-width:610px;margin:0}.feature-list{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.8rem;margin-top:2.1rem}.feature-item{border:1px solid rgba(255,255,255,.12);background:rgba(15,23,42,.32);border-radius:12px;padding:1rem;backdrop-filter:blur(10px)}.feature-item strong{display:block;color:#fff;font-size:.85rem;margin:.55rem 0 .2rem}.feature-item span{display:block;color:#94a3b8;font-size:.75rem;line-height:1.45}.login-foot{font-size:.75rem;color:#64748b}.login-panel{display:flex;align-items:center;justify-content:center;padding:2rem;background:linear-gradient(180deg,#fff,#f8fafc)}.login-card{width:min(100%,440px);padding:2rem}.login-card h2{font-size:1.65rem;letter-spacing:-.025em;margin:0 0 .4rem}.login-card>p{color:#64748b;line-height:1.55;margin:0 0 1.75rem}.form-field{margin-bottom:1rem}.password-wrap{position:relative}.password-wrap .ui-input{padding-right:3rem}.password-toggle{position:absolute;right:.35rem;top:50%;transform:translateY(-50%);width:34px;height:34px}.login-error{margin:.75rem 0 0}.login-meta{display:flex;align-items:center;justify-content:center;gap:.5rem;margin-top:1.25rem;color:#94a3b8;font-size:.75rem}
/* Dashboard */
.topbar{position:sticky;top:0;z-index:40;border-bottom:1px solid rgba(226,232,240,.9);background:rgba(248,250,252,.86);backdrop-filter:blur(14px)}.topbar-inner{max-width:80rem;margin:0 auto;height:68px;padding:0 1.5rem;display:flex;align-items:center;justify-content:space-between}.topbar-brand{display:flex;align-items:center;gap:.8rem;text-decoration:none}.topbar-brand strong{display:block;font-size:.92rem}.topbar-brand span{display:block;font-size:.72rem;color:#64748b;margin-top:.1rem}.user-menu{display:flex;align-items:center;gap:.65rem}.user-chip{display:flex;align-items:center;gap:.55rem;padding:.36rem .7rem;border:1px solid var(--border);background:#fff;border-radius:999px;font-size:.78rem;color:#475569}.avatar{width:27px;height:27px;border-radius:50%;display:grid;place-items:center;background:#eef2ff;color:#4338ca;font-weight:800;font-size:.72rem}
.dashboard-main{max-width:80rem;margin:0 auto;padding:2.25rem 1.5rem 4rem}.dashboard-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:1rem;margin-bottom:1.4rem}.eyebrow{display:flex;align-items:center;gap:.45rem;color:#6366f1;font-size:.75rem;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.dashboard-heading h1{font-size:clamp(1.8rem,3vw,2.5rem);line-height:1.15;letter-spacing:-.035em;margin:.35rem 0 .4rem}.dashboard-heading p{margin:0;color:#64748b;line-height:1.6}.platform-state{display:flex;align-items:center;gap:.5rem;border:1px solid var(--border);background:#fff;border-radius:999px;padding:.45rem .7rem;font-size:.75rem;font-weight:600;color:#475569;white-space:nowrap}
.stats-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:1rem;margin:1.4rem 0}.stat-card{padding:1.05rem 1.1rem}.stat-head{display:flex;align-items:center;justify-content:space-between;color:#64748b;font-size:.75rem;font-weight:700}.stat-icon{width:32px;height:32px;border-radius:9px;display:grid;place-items:center;background:#f8fafc;border:1px solid var(--border);color:#6366f1}.stat-value{font-size:1.6rem;font-weight:800;letter-spacing:-.025em;margin-top:.55rem}.stat-sub{font-size:.72rem;color:#94a3b8;margin-top:.15rem}
.start-panel{padding:1.15rem;margin:1rem 0 1.5rem}.start-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:.75rem;align-items:end}.start-title{display:flex;align-items:center;gap:.6rem;font-weight:700;margin-bottom:.75rem}.start-help{font-size:.75rem;color:#64748b;margin-top:.5rem}.section-head{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin:1.65rem 0 .8rem}.section-head h2{font-size:1.05rem;margin:0}.section-head span{font-size:.75rem;color:#64748b}.workspace-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}.workspace-card{padding:1.1rem;min-height:205px;display:flex;flex-direction:column;transition:transform .15s ease,border-color .15s ease,box-shadow .15s ease}.workspace-card:hover{transform:translateY(-1px);border-color:#cbd5e1;box-shadow:0 10px 25px rgba(15,23,42,.065)}.workspace-card-head{display:flex;align-items:flex-start;justify-content:space-between;gap:.75rem}.workspace-icon{width:38px;height:38px;border-radius:10px;display:grid;place-items:center;background:#eef2ff;color:#4f46e5;border:1px solid #e0e7ff}.workspace-card h3{font-size:.97rem;margin:.85rem 0 .2rem;overflow-wrap:anywhere}.workspace-sub{font-size:.75rem;color:#64748b;min-height:1rem}.workspace-meta{display:flex;align-items:center;gap:.45rem;flex-wrap:wrap;margin:.85rem 0 1rem;font-size:.72rem;color:#64748b}.meta-pill{display:inline-flex;align-items:center;gap:.3rem;border-radius:6px;background:#f8fafc;border:1px solid #e2e8f0;padding:.28rem .45rem}.workspace-actions{display:flex;gap:.55rem;margin-top:auto}.workspace-actions .ui-button{flex:1}.empty-state{grid-column:1/-1;text-align:center;padding:3rem 1rem}.empty-icon{width:52px;height:52px;border-radius:15px;display:grid;place-items:center;margin:0 auto .9rem;background:#eef2ff;color:#4f46e5}.empty-state h3{margin:.2rem 0;font-size:1rem}.empty-state p{margin:.3rem auto 0;color:#64748b;font-size:.84rem;max-width:420px;line-height:1.55}
.skeleton{position:relative;overflow:hidden;background:#e2e8f0;border-radius:7px}.skeleton:after{content:"";position:absolute;inset:0;transform:translateX(-100%);background:linear-gradient(90deg,transparent,rgba(255,255,255,.68),transparent);animation:shimmer 1.3s infinite}@keyframes shimmer{100%{transform:translateX(100%)}}.skeleton-card{height:205px;border-radius:12px;border:1px solid #e2e8f0;background:#fff;padding:1rem}.skel-line{height:12px;margin:.65rem 0}.skel-line.short{width:42%}.skel-line.medium{width:68%}
.busy-overlay{position:fixed;inset:0;z-index:100;background:rgba(248,250,252,.84);display:flex;align-items:center;justify-content:center;padding:1rem;backdrop-filter:blur(7px)}.busy-overlay[hidden]{display:none}.busy-card{width:min(500px,100%);padding:1.5rem;text-align:center}.busy-ring{width:48px;height:48px;border-radius:50%;margin:0 auto 1rem;background:conic-gradient(#4f46e5 0 28%,#e2e8f0 28% 100%);position:relative;animation:spin .9s linear infinite}.busy-ring:after{content:"";position:absolute;inset:4px;background:#fff;border-radius:50%}.busy-card h3{font-size:1.05rem;margin:.1rem 0 .45rem}.busy-card p{margin:0;color:#64748b;font-size:.83rem;line-height:1.55}.progress-track{height:4px;background:#e2e8f0;border-radius:99px;overflow:hidden;margin-top:1rem}.progress-bar{height:100%;width:35%;background:linear-gradient(90deg,#4f46e5,#0ea5e9);border-radius:99px;animation:progress 1.45s ease-in-out infinite}@keyframes progress{0%{transform:translateX(-100%)}100%{transform:translateX(385%)}}
.toast-region{position:fixed;right:1rem;bottom:1rem;z-index:120;display:flex;flex-direction:column;gap:.6rem;width:min(390px,calc(100vw - 2rem))}.toast{display:flex;gap:.7rem;align-items:flex-start;background:#0f172a;color:#f8fafc;border:1px solid #334155;border-radius:10px;padding:.85rem .95rem;box-shadow:0 15px 40px rgba(15,23,42,.3);animation:toast-in .18s ease-out}.toast.error{background:#7f1d1d;border-color:#991b1b}.toast.success{background:#064e3b;border-color:#047857}.toast-title{font-size:.82rem;font-weight:700}.toast-message{font-size:.75rem;color:#cbd5e1;margin-top:.1rem;line-height:1.45}@keyframes toast-in{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}
.ui-dialog{border:0;border-radius:14px;padding:0;width:min(430px,calc(100vw - 2rem));box-shadow:0 24px 70px rgba(15,23,42,.28);background:#fff;color:#0f172a}.ui-dialog::backdrop{background:rgba(15,23,42,.42);backdrop-filter:blur(3px)}.dialog-body{padding:1.35rem}.dialog-head{display:flex;gap:.8rem;align-items:flex-start}.dialog-icon{width:38px;height:38px;border-radius:10px;display:grid;place-items:center;background:#fef2f2;color:#dc2626}.dialog-head h3{margin:0;font-size:1rem}.dialog-head p{margin:.35rem 0 0;color:#64748b;font-size:.8rem;line-height:1.5}.dialog-actions{display:flex;justify-content:flex-end;gap:.55rem;padding:1rem 1.35rem;border-top:1px solid var(--border);background:#f8fafc;border-radius:0 0 14px 14px}
@media(max-width:1024px){.login-shell{grid-template-columns:1fr}.login-visual{display:none}.login-panel{min-height:100vh}.stats-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.workspace-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:700px){.topbar-inner,.dashboard-main{padding-left:1rem;padding-right:1rem}.dashboard-heading{align-items:flex-start;flex-direction:column}.platform-state{display:none}.stats-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem}.stat-card{padding:.85rem}.stat-value{font-size:1.35rem}.start-row{grid-template-columns:1fr}.workspace-grid{grid-template-columns:1fr}.user-chip{display:none}.workspace-card{min-height:190px}.login-panel{padding:1rem}.login-card{padding:1.4rem}.topbar-brand span{display:none}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
'''.strip()


def _icon(name: str, cls: str = "icon") -> str:
    icons = {
        "terminal": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="m7 8 4 4-4 4"/><path d="M13 16h4"/></svg>',
        "shield": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M20 13c0 5-3.5 7.5-8 9-4.5-1.5-8-4-8-9V5l8-3 8 3v8Z"/><path d="m9 12 2 2 4-4"/></svg>',
        "database": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5"/><path d="M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6"/></svg>',
        "refresh": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M20 11a8 8 0 1 0-2.4 5.7"/><path d="M20 4v7h-7"/></svg>',
        "user": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21a7 7 0 0 0-14 0"/><circle cx="12" cy="7" r="4"/></svg>',
        "lock": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect width="16" height="12" x="4" y="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>',
        "eye": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg>',
        "logout": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M10 17l5-5-5-5"/><path d="M15 12H3"/><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/></svg>',
        "plus": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M12 5v14M5 12h14"/></svg>',
        "code": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="m8 9-3 3 3 3"/><path d="m16 9 3 3-3 3"/><path d="m14 5-4 14"/></svg>',
        "play": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><path d="m6 3 14 9-14 9V3Z"/></svg>',
        "stop": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="5" y="5" rx="2"/></svg>',
        "external": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M15 3h6v6"/><path d="m10 14 11-11"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/></svg>',
        "layers": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="m12 2 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5"/><path d="m3 17 9 5 9-5"/></svg>',
        "activity": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12h4l2-6 4 12 2-6h6"/></svg>',
        "clock": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>',
        "server": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="7" x="3" y="3" rx="2"/><rect width="18" height="7" x="3" y="14" rx="2"/><path d="M7 6.5h.01M7 17.5h.01"/></svg>',
        "alert": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3 2.7 19h18.6L12 3Z"/><path d="M12 9v4M12 17h.01"/></svg>',
        "check": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m5 12 4 4L19 6"/></svg>',
        "x": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="m6 6 12 12M18 6 6 18"/></svg>',
    }
    return icons.get(name, icons["code"]).replace("<svg ", f'<svg class="{cls}" ')


def login_page_html() -> str:
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in · OpenCode Workspace Portal</title><link rel="stylesheet" href="/_ui/app.css"></head>
<body>
<main class="login-shell">
  <section class="login-visual" aria-hidden="true">
    <div class="login-brand"><span class="brand-mark">{_icon("terminal")}</span><div>OpenCode Workspace Portal<small>Internal developer platform</small></div></div>
    <div class="login-hero">
      <span class="login-kicker"><span class="status-dot"></span> Secure multi-user workspace gateway</span>
      <h1>Developer workspaces, isolated and ready on demand.</h1>
      <p>Launch persistent OpenCode environments without managing containers, credentials, or runtime cleanup manually.</p>
      <div class="feature-list">
        <div class="feature-item">{_icon("shield")}<strong>Isolated runtimes</strong><span>Dedicated rootless containers and resource controls per workspace.</span></div>
        <div class="feature-item">{_icon("database")}<strong>Persistent state</strong><span>Your projects and OpenCode sessions survive runtime recreation.</span></div>
        <div class="feature-item">{_icon("refresh")}<strong>Automatic cleanup</strong><span>Idle runtimes are reclaimed while your workspace data remains available.</span></div>
      </div>
    </div>
    <div class="login-foot">OpenCode Multiuser · Enterprise workspace gateway</div>
  </section>
  <section class="login-panel app-grid-bg">
    <div class="ui-card ui-card-elevated login-card">
      <div style="display:flex;align-items:center;gap:.75rem;margin-bottom:1.2rem"><span class="brand-mark">{_icon("terminal")}</span><div><strong style="display:block;font-size:.9rem">OpenCode</strong><span class="text-xs text-muted">Workspace Portal</span></div></div>
      <h2>Welcome back</h2><p>Sign in with your developer platform credentials to access your workspaces.</p>
      <form id="login" novalidate>
        <div class="form-field"><label class="ui-label" for="username">Username</label><input class="ui-input" id="username" name="username" autocomplete="username" placeholder="Enter your username" required></div>
        <div class="form-field"><label class="ui-label" for="password">Password</label><div class="password-wrap"><input class="ui-input" id="password" name="password" type="password" autocomplete="current-password" placeholder="Enter your password" required><button id="toggle-password" class="ui-icon-button password-toggle" type="button" aria-label="Show password">{_icon("eye")}</button></div></div>
        <div id="login-error" class="ui-alert ui-alert-error login-error hidden" role="alert"><span>{_icon("alert")}</span><span id="login-error-text">Unable to sign in.</span></div>
        <button id="login-button" class="ui-button ui-button-primary w-full" style="margin-top:1rem" type="submit"><span id="login-spinner" class="ui-spinner hidden"></span><span id="login-button-text">Sign in</span></button>
      </form>
      <div class="login-meta">{_icon("shield","icon-sm")} <span>Secure internal access · Session protected</span></div>
    </div>
  </section>
</main>
<script>
const form=document.getElementById('login'),button=document.getElementById('login-button'),spinner=document.getElementById('login-spinner'),buttonText=document.getElementById('login-button-text'),errorBox=document.getElementById('login-error'),errorText=document.getElementById('login-error-text');
document.getElementById('toggle-password').addEventListener('click',()=>{{const p=document.getElementById('password'); const reveal=p.type==='password'; p.type=reveal?'text':'password'; document.getElementById('toggle-password').setAttribute('aria-label',reveal?'Hide password':'Show password');}});
form.addEventListener('submit',async(e)=>{{e.preventDefault(); errorBox.classList.add('hidden'); if(!form.reportValidity()) return; button.disabled=true; spinner.classList.remove('hidden'); buttonText.textContent='Signing in…'; try{{const r=await fetch('/auth/login',{{method:'POST',headers:{{'content-type':'application/json'}},credentials:'same-origin',body:JSON.stringify({{username:document.getElementById('username').value.trim(),password:document.getElementById('password').value}})}}); if(!r.ok){{let msg='Unable to sign in. Check your credentials and try again.'; try{{const j=await r.json(); if(j.detail) msg=typeof j.detail==='string'?j.detail:msg}}catch(_){{}} throw new Error(msg)}} window.location.assign('/dashboard')}}catch(err){{errorText.textContent=err.message; errorBox.classList.remove('hidden'); button.disabled=false; spinner.classList.add('hidden'); buttonText.textContent='Sign in'; document.getElementById('password').focus();}}}});
</script></body></html>'''


def dashboard_page_html(username: str, notice_html: str, max_slots: int, free_slots: int, idle_minutes: int) -> str:
    safe_user = escape(username)
    initials = escape((username[:2] or "U").upper())
    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Workspaces · OpenCode</title><link rel="stylesheet" href="/_ui/app.css"></head>
<body class="app-grid-bg">
<header class="topbar"><div class="topbar-inner"><a class="topbar-brand" href="/dashboard"><span class="brand-mark">{_icon("terminal")}</span><div><strong>OpenCode</strong><span>Workspace Portal</span></div></a><div class="user-menu"><div class="user-chip"><span class="avatar">{initials}</span><span>{safe_user}</span></div><form id="logout-form" method="post" action="/logout"><button class="ui-button ui-button-ghost" type="submit">{_icon("logout","icon-sm")} Logout</button></form></div></div></header>
<main class="dashboard-main">
  <div class="dashboard-heading"><div><div class="eyebrow">{_icon("layers","icon-sm")} Developer platform</div><h1>Your workspaces</h1><p>Start, resume, and manage isolated OpenCode development environments.</p></div><div class="platform-state"><span class="status-dot"></span> Platform online</div></div>
  {notice_html}
  <section class="stats-grid" aria-label="Workspace statistics">
    <div class="ui-card stat-card"><div class="stat-head"><span>Projects</span><span class="stat-icon">{_icon("layers","icon-sm")}</span></div><div id="stat-projects" class="stat-value">—</div><div class="stat-sub">Visible to your account</div></div>
    <div class="ui-card stat-card"><div class="stat-head"><span>Running</span><span class="stat-icon">{_icon("activity","icon-sm")}</span></div><div id="stat-running" class="stat-value">—</div><div class="stat-sub">Active workspace runtimes</div></div>
    <div class="ui-card stat-card"><div class="stat-head"><span>Available slots</span><span class="stat-icon">{_icon("server","icon-sm")}</span></div><div id="stat-free" class="stat-value">{free_slots}</div><div class="stat-sub">of {max_slots} total runtime slots</div></div>
    <div class="ui-card stat-card"><div class="stat-head"><span>Idle timeout</span><span class="stat-icon">{_icon("clock","icon-sm")}</span></div><div class="stat-value">{idle_minutes}<span style="font-size:.8rem;font-weight:700;color:#64748b;margin-left:.15rem">min</span></div><div class="stat-sub">Unused runtimes are reclaimed</div></div>
  </section>
  <section class="ui-card start-panel">
    <div class="start-title"><span class="workspace-icon" style="width:32px;height:32px">{_icon("plus","icon-sm")}</span><span>Start a workspace</span></div>
    <form id="new" class="start-row"><div><label class="ui-label" for="project">Project slug</label><input class="ui-input" id="project" required pattern="[A-Za-z0-9_.-]+" placeholder="e.g. agentic-ai-platform" autocomplete="off"><div class="start-help">Letters, numbers, dots, underscores, and hyphens only. Existing project data will be reused automatically.</div></div><button id="start-new" class="ui-button ui-button-primary" type="submit">{_icon("play","icon-sm")} Start workspace</button></form>
  </section>
  <div class="section-head"><div><h2>Projects & workspaces</h2><span>Runtime state and available actions</span></div><button id="refresh-button" class="ui-button ui-button-secondary" type="button">{_icon("refresh","icon-sm")} Refresh</button></div>
  <section id="list" class="workspace-grid" aria-live="polite">
    <div class="skeleton-card"><div class="skeleton skel-line short"></div><div class="skeleton skel-line medium"></div></div><div class="skeleton-card"><div class="skeleton skel-line short"></div><div class="skeleton skel-line medium"></div></div><div class="skeleton-card"><div class="skeleton skel-line short"></div><div class="skeleton skel-line medium"></div></div>
  </section>
</main>
<div id="busy" class="busy-overlay" hidden aria-live="polite" aria-busy="true"><div class="ui-card ui-card-elevated busy-card"><div class="busy-ring"></div><h3 id="busy-title">Working…</h3><p id="busy-detail"></p><div class="progress-track"><div class="progress-bar"></div></div></div></div>
<div id="toasts" class="toast-region" aria-live="polite" aria-atomic="true"></div>
<dialog id="stop-dialog" class="ui-dialog"><div class="dialog-body"><div class="dialog-head"><span class="dialog-icon">{_icon("stop")}</span><div><h3>Stop workspace?</h3><p id="stop-dialog-text">The runtime container will be stopped and its slot freed. Your project files and OpenCode state will remain available.</p></div></div></div><div class="dialog-actions"><button id="stop-cancel" class="ui-button ui-button-secondary" type="button">Cancel</button><button id="stop-confirm" class="ui-button ui-button-danger" type="button">Stop workspace</button></div></dialog>
<script>
const busy=document.getElementById('busy'),busyTitle=document.getElementById('busy-title'),busyDetail=document.getElementById('busy-detail'),list=document.getElementById('list'),toasts=document.getElementById('toasts');let pendingStop=null,busyTimer=null;
function esc(v){{return String(v??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]))}}
function toast(title,message,type='success'){{const el=document.createElement('div');el.className='toast '+type;el.innerHTML=`<span>${{type==='error'?'⚠':'✓'}}</span><div><div class="toast-title">${{esc(title)}}</div><div class="toast-message">${{esc(message)}}</div></div>`;toasts.appendChild(el);setTimeout(()=>el.remove(),4500)}}
function setBusy(title,detail,stages=[]){{busyTitle.textContent=title;busyDetail.textContent=detail;busy.hidden=false;document.querySelectorAll('button').forEach(b=>b.disabled=true);if(busyTimer)clearInterval(busyTimer);let i=0;if(stages.length){{busyDetail.textContent=stages[0];busyTimer=setInterval(()=>{{i=Math.min(i+1,stages.length-1);busyDetail.textContent=stages[i];}},1700)}}}}
function hideBusy(){{busy.hidden=true;document.querySelectorAll('button').forEach(b=>b.disabled=false);if(busyTimer)clearInterval(busyTimer);busyTimer=null}}
async function api(url,opts={{}}){{const r=await fetch(url,{{credentials:'same-origin',...opts}});if(!r.ok){{let msg=r.statusText;try{{const j=await r.json();msg=typeof j.detail==='string'?j.detail:(j.detail?.message||JSON.stringify(j.detail))}}catch(_){{}}throw new Error(msg)}}return r.status===204?null:r.json()}}
function badge(status){{const s=(status||'unknown').toLowerCase();return `<span class="ui-badge badge-${{esc(s)}}">${{esc(s)}}</span>`}}
function workspaceCard(w){{const running=w.status==='running',legacy=running&&!w.url,stopped=w.status==='stopped'||w.status==='error';const c=document.createElement('article');c.className='ui-card workspace-card';c.innerHTML=`<div class="workspace-card-head"><span class="workspace-icon">${{`{_icon("code")}`}}</span>${{badge(w.status)}}</div><h3>${{esc(w.project_slug)}}</h3><div class="workspace-sub">${{running?'Runtime available and ready for use.':w.status==='error'?'The last runtime failed. Start it again to retry.':'Persistent workspace data is available.'}}</div><div class="workspace-meta"><span class="meta-pill">Slot ${{esc(w.slot_id??'—')}}</span>${{w.container_name?`<span class="meta-pill" title="${{esc(w.container_name)}}">${{esc(w.container_name)}}</span>`:''}}</div><div class="workspace-actions"></div>`;const actions=c.querySelector('.workspace-actions');if(running&&w.url){{const a=document.createElement('a');a.className='ui-button ui-button-primary';a.href=w.url;a.innerHTML=`{_icon("external","icon-sm")} Open`;actions.appendChild(a);const b=document.createElement('button');b.className='ui-button ui-button-secondary';b.type='button';b.innerHTML=`{_icon("stop","icon-sm")} Stop`;b.onclick=()=>askStop(w);actions.appendChild(b)}}else if(legacy){{const b=document.createElement('button');b.className='ui-button ui-button-primary';b.type='button';b.innerHTML=`{_icon("refresh","icon-sm")} Upgrade runtime`;b.onclick=()=>startProject(w.project_slug);actions.appendChild(b)}}else if(stopped){{const b=document.createElement('button');b.className='ui-button ui-button-primary';b.type='button';b.innerHTML=`{_icon("play","icon-sm")} Start`;b.onclick=()=>startProject(w.project_slug);actions.appendChild(b)}}return c}}
async function refresh(silent=false){{if(!silent)document.getElementById('refresh-button').disabled=true;try{{const rows=await api('/workspaces');list.innerHTML='';document.getElementById('stat-projects').textContent=rows.length;document.getElementById('stat-running').textContent=rows.filter(w=>w.status==='running').length;if(!rows.length){{list.innerHTML=`<div class="ui-card empty-state"><div class="empty-icon">{_icon("code")}</div><h3>No workspaces yet</h3><p>Start your first project above. A dedicated OpenCode runtime will be created and connected automatically.</p></div>`}}else rows.forEach(w=>list.appendChild(workspaceCard(w)));try{{const o=await api('/_portal/overview');document.getElementById('stat-free').textContent=o.free_slots}}catch(_){{}}}}catch(err){{list.innerHTML=`<div class="ui-card empty-state"><div class="empty-icon" style="color:#dc2626;background:#fef2f2">{_icon("alert")}</div><h3>Unable to load workspaces</h3><p>${{esc(err.message)}}</p></div>`;toast('Unable to refresh',err.message,'error')}}finally{{document.getElementById('refresh-button').disabled=false}}}}
async function startProject(slug){{setBusy('Starting workspace…','Starting container…',['Starting container…','Waiting for OpenCode service…','Finalizing secure gateway…','Opening workspace…']);try{{const x=await api('/workspaces/start',{{method:'POST',headers:{{'content-type':'application/json'}},body:JSON.stringify({{project_slug:slug}})}});busyDetail.textContent='Opening workspace…';window.location.assign(x.url)}}catch(err){{hideBusy();toast('Workspace failed to start',err.message,'error');await refresh(true)}}}}
function askStop(w){{pendingStop=w;document.getElementById('stop-dialog-text').textContent=`Stop ${{w.project_slug}}? The runtime container will be stopped and its slot freed. Your persistent workspace data will be kept.`;document.getElementById('stop-dialog').showModal()}}
async function stopProject(w){{setBusy('Stopping workspace…','Stopping container…',['Stopping container…','Freeing runtime slot…','Updating workspace status…']);try{{await api('/workspaces/'+w.id+'/stop',{{method:'POST'}});hideBusy();toast('Workspace stopped',`${{w.project_slug}} is stopped and its slot is now available.`);await refresh(true)}}catch(err){{hideBusy();toast('Unable to stop workspace',err.message,'error')}}}}
document.getElementById('new').addEventListener('submit',e=>{{e.preventDefault();if(!e.currentTarget.reportValidity())return;startProject(document.getElementById('project').value.trim())}});document.getElementById('refresh-button').onclick=()=>refresh();document.getElementById('stop-cancel').onclick=()=>document.getElementById('stop-dialog').close();document.getElementById('stop-confirm').onclick=()=>{{document.getElementById('stop-dialog').close();if(pendingStop)stopProject(pendingStop)}};
document.getElementById('logout-form').addEventListener('submit',async e=>{{e.preventDefault();setBusy('Logging out…','Stopping active workspaces…',['Stopping active workspaces…','Freeing runtime slots…','Ending your session…']);try{{await fetch('/logout',{{method:'POST',credentials:'same-origin'}});window.location.assign('/login')}}catch(err){{hideBusy();toast('Logout failed',err.message,'error')}}}});
refresh();
</script></body></html>'''
